local:
  kafka:
    host: 10.221.246.27

spring:
  kafka:
#    consumer:
#      auto-offset-reset: earliest
    bootstrap-servers:
      - ${local.kafka.host}:9093
      - ${local.kafka.host}:9094
      - ${local.kafka.host}:9095